name: Validate build

on: 
  push:

jobs:
  validate-build:

    runs-on: windows-latest

    steps:

    - name: First job
      run: echo first job
    - name: Second job
      run: echo second job
