name: Validate build

on: 
  push:
  pull_request:

jobs:
  validate-build:

    runs-on: windows-latest

    strategy:
      matrix:
        include:
#           - os: macos-latest
#             TARGET: macos
#             CMD_BUILD: pyinstaller hello.spec
#             OUT_FILE_NAME: hello.zip
#             ASSET_MIME: application/zip
          - os: windows-latest
            target: windows
            python-version: '3.10'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python - ${{matrix.os}} - ${{matrix.python-version}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}
        cache: 'pip'
    - run: pip install -r requirements.txt

    # - name: Cache PIP
    #   uses: actions/cache@v2
    #   with:
    #     path: ~/.cache/pip
    #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('requirements.txt') }}
        
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install pyinstaller
    #     pip install -r requirements.txt

    - name: Unit tests
      run: pytest
    